#!/usr/bin/env python3
"""Import the /merci landing page "as is" from the former Astro site (techflow-site).

The page was built and validated in the Astro project; it is kept pixel-identical here instead of
being rewritten as React components. This script takes the Astro build output (dist/merci) and:
  - copies its CSS (one file), fonts, local images and hls.js under public/lp/merci/,
  - downloads every image still served by the Webflow CDN (Webflow is being cancelled),
  - rewrites every URL to those local copies,
  - writes the HTML to src/landing/merci-html.ts, served by src/app/[lang]/merci/route.ts.

Usage: python3 scripts/landing/import-merci.py ~/Projects/techflow-site  (run `npm run build` there first)
"""
import hashlib, json, pathlib, re, sys, urllib.parse, urllib.request

src = pathlib.Path(sys.argv[1]).expanduser()
dist = src / "dist"
repo = pathlib.Path(__file__).resolve().parents[2]
out = repo / "public/lp/merci"
for d in ("img", "fonts", "js"):
    (out / d).mkdir(parents=True, exist_ok=True)

html = (dist / "merci/index.html").read_text()

# 1. CSS: concatenate the stylesheets in their original order, then drop the <link> tags.
css = ""
for href in re.findall(r'<link rel="stylesheet" href="(/_astro/[^"]+)">', html):
    css += (dist / href.lstrip("/")).read_text() + "\n"
html = re.sub(r'<link rel="stylesheet" href="/_astro/[^"]+">', "", html)

def font(m):
    name = m.group(1)
    (out / "fonts" / name).write_bytes((src / "public/fonts" / name).read_bytes())
    return f"url(/lp/merci/fonts/{name})"
css = re.sub(r"url\(/fonts/([^)]+)\)", font, css)

# 2. Remote images (Webflow CDN) -> local copies. Mux thumbnails/streams stay on Mux.
def localize(url):
    name = urllib.parse.unquote(url.rsplit("/", 1)[1].split("?")[0])
    name = re.sub(r"[^A-Za-z0-9._-]+", "-", name)
    name = f"{hashlib.sha1(url.encode()).hexdigest()[:6]}-{name}"
    dest = out / "img" / name
    if not dest.exists():
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        dest.write_bytes(urllib.request.urlopen(req, timeout=30).read())
    return f"/lp/merci/img/{name}"

webflow = sorted(set(re.findall(r'https://cdn\.prod\.website-files\.com/[^"\'\s)]+', html + css)))
for url in webflow:
    local = localize(url)
    html = html.replace(url, local)
    css = css.replace(url, local)

# 3. Local images of the Astro site.
for path in sorted(set(re.findall(r'"/images/([^"]+)"', html))):
    if path.startswith("tf-icon"):
        continue
    (out / "img" / path).write_bytes((src / "public/images" / path).read_bytes())
    html = html.replace(f'"/images/{path}"', f'"/lp/merci/img/{path}"')

# 4. Favicons: use the new site's icons.
html = re.sub(r'<link rel="(icon|apple-touch-icon)"[^>]*>', "", html)
html = html.replace("</title>", '</title><link rel="icon" href="/favicon.ico" sizes="any"><link rel="icon" href="/icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/apple-icon.png">', 1)

# 5. hls.js (Mux testimonials) self-hosted instead of jsDelivr.
hls = "https://cdn.jsdelivr.net/npm/hls.js@1.5.17/dist/hls.min.js"
if hls in html:
    req = urllib.request.Request(hls, headers={"User-Agent": "Mozilla/5.0"})
    (out / "js/hls-1.5.17.min.js").write_bytes(urllib.request.urlopen(req, timeout=30).read())
    html = html.replace(hls, "/lp/merci/js/hls-1.5.17.min.js")

# 6. Legal links: relative, straight to the current pages.
html = html.replace("https://www.techflow-agency.com/politique-de-cookies", "/politique-de-confidentialite")
html = html.replace("https://www.techflow-agency.com/", "/")

(out / "merci.css").write_text(css)
html = html.replace("</head>", '<link rel="stylesheet" href="/lp/merci/merci.css"></head>', 1)

left = re.findall(r'https://cdn\.prod\.website-files\.com|/_astro/|"/images/|"/fonts/', html + css)
assert not left, f"unconverted URLs: {left}"

ts = ("// Generated by scripts/landing/import-merci.py from the former Astro site (techflow-site, src/pages/merci.astro).\n"
      "// Do not edit by hand: change the Astro page, rebuild it and re-run the script.\n"
      f"export const merciHtml = {json.dumps(html, ensure_ascii=False)};\n")
(repo / "src/landing").mkdir(exist_ok=True)
(repo / "src/landing/merci-html.ts").write_text(ts)
print(f"{len(webflow)} Webflow images localized, html {len(html)} chars, css {len(css)} chars")
